# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# temp file, all of this to be handled elsewhere in final version 
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BEACONS = [
    "https://rsrq.bento.sd4h.ca/api/beacon",
    "https://bqc19.bento.sd4h.ca/api/beacon",
    # "https://staging.bqc19.bento.sd4h.ca/api/beacon",
    "https://staging.bento.sd4h.ca/api/beacon",
    "https://ichange.bento.sd4h.ca/api/beacon",
    # "https://qa.bento.sd4h.ca/api/beacon/",
    # "https://bentov2.local/api/beacon",
]

NETWORK_TIMEOUT = 30

VALID_ENDPOINTS = ["analyses", "biosamples", "cohorts", "datasets", "g_variants", "individuals", "runs", "overview"]

KATSU_CONFIG_UNION = [
    {
        "section_title": "General",
        "fields": [
            {
                "mapping": "individual/age_numeric",
                "title": "Age",
                "description": "Age at arrival",
                "datatype": "number",
                "config": {
                    "bin_size": 10,
                    "taper_left": 10,
                    "taper_right": 100,
                    "units": "years",
                    "minimum": 0,
                    "maximum": 100,
                },
                "id": "age",
                "options": [
                    "< 10",
                    "[10, 20)",
                    "[20, 30)",
                    "[30, 40)",
                    "[40, 50)",
                    "[50, 60)",
                    "[60, 70)",
                    "[70, 80)",
                    "[80, 90)",
                    "[90, 100)",
                ],
            },
            {
                "mapping": "individual/sex",
                "title": "Sex",
                "description": "Sex at birth",
                "datatype": "string",
                "config": {"enum": None},
                "id": "sex",
                "options": ["MALE", "FEMALE"],
            },
            {
                "mapping": "individual/extra_properties/date_of_consent",
                "title": "Verbal consent date",
                "description": "Date of initial verbal consent (participant, legal representative or tutor), yyyy-mm-dd",
                "datatype": "date",
                "config": {"bin_by": "month"},
                "id": "date_of_consent",
                "options": [
                    "Jan 2020",
                    "Feb 2020",
                    "Mar 2020",
                    "Apr 2020",
                    "May 2020",
                    "Jun 2020",
                    "Jul 2020",
                    "Aug 2020",
                    "Sep 2020",
                    "Oct 2020",
                    "Nov 2020",
                    "Dec 2020",
                    "Jan 2021",
                    "Feb 2021",
                    "Mar 2021",
                    "Apr 2021",
                    "May 2021",
                    "Jun 2021",
                    "Jul 2021",
                    "Aug 2021",
                    "Sep 2021",
                    "Oct 2021",
                    "Nov 2021",
                    "Dec 2021",
                    "Jan 2022",
                    "Feb 2022",
                    "Mar 2022",
                    "Apr 2022",
                    "May 2022",
                    "Jun 2022",
                    "Jul 2022",
                    "Aug 2022",
                    "Sep 2022",
                    "Oct 2022",
                    "Nov 2022",
                    "Dec 2022",
                    "Jan 2023",
                    "Feb 2023",
                    "Mar 2023",
                    "Apr 2023",
                    "May 2023",
                    "Jun 2023",
                    "Jul 2023",
                    "Aug 2023",
                    "Sep 2023",
                    "Oct 2023",
                    "Nov 2023",
                    "Dec 2023",
                ],
            },
            {
                "mapping": "individual/extra_properties/mobility",
                "title": "Functional status",
                "description": "Mobility",
                "datatype": "string",
                "config": {
                    "enum": [
                        "I have no problems in walking about",
                        "I have slight problems in walking about",
                        "I have moderate problems in walking about",
                        "I have severe problems in walking about",
                        "I am unable to walk about",
                    ]
                },
                "id": "mobility",
                "options": [
                    "I have no problems in walking about",
                    "I have slight problems in walking about",
                    "I have moderate problems in walking about",
                    "I have severe problems in walking about",
                    "I am unable to walk about",
                ],
            },
            {
                "mapping": "individual/extra_properties/covid_severity",
                "title": "Covid severity",
                "description": "Covid severity",
                "datatype": "string",
                "config": {"enum": ["Uninfected", "Mild", "Moderate", "Severe", "Dead"]},
                "id": "covid_severity",
                "options": ["Uninfected", "Mild", "Moderate", "Severe", "Dead"],
            },
            {
                "mapping": "individual/phenopackets/phenotypic_features/pftype/label",
                "title": "Phenotypic Features",
                "description": "Individual phenotypic features, observed as either present or absent",
                "datatype": "string",
                "config": {"enum": None},
                "id": "phenotypic_features",
                "options": [
                    "Loss of appetite",
                    "Asthma",
                    "Abdominal pain",
                    "Headache",
                    "Cough",
                    "Cardiac arrest",
                    "Nausea",
                    "Pulmonary hypertension",
                    "Viral pneumonia/pneumonitis",
                    "HIV Infection",
                    "Hyperglycemia",
                    "Patient immunosuppressed",
                    "Fever",
                    "Chest pain",
                    "Pneumothorax",
                    "Hypertension",
                    "Dementia",
                    "Loss of sense of smell",
                ],
            },
            {
                "mapping": "individual/phenopackets/diseases/term/label",
                "title": "Diseases",
                "description": "Diseases observed as either present or absent",
                "datatype": "string",
                "config": {"enum": None},
                "id": "diseases",
                "options": [
                    "viral pneumonia",
                    "Glioblastoma",
                    "Polycythemia vera",
                    "Miller syndrome",
                    "Cystic fibrosis",
                    "coronary artery disease, autosomal dominant, 1",
                    "Hashimoto Thyroiditis",
                    "Rheumatologic disease",
                    "Takotsubo cardiomyopathy",
                    "autoimmune disorder of cardiovascular system",
                    "COVID-19",
                    "Marfan syndrome",
                    "Non-Hodgkin Lymphoma",
                    "diabetes mellitus",
                ],
            },
            {
                "mapping": "biosample/sampled_tissue/label",
                "mapping_for_search_filter": "individual/biosamples/sampled_tissue/label",
                "title": "Sampled Tissues",
                "description": "Tissue from which the biosample was extracted",
                "datatype": "string",
                "config": {"enum": None},
                "id": "tissues",
                "options": ["Plasma", "blood", "Serum"],
            },
        ],
    },
    {
        "section_title": "Measurements",
        "fields": [
            {
                "mapping": "individual/extra_properties/lab_test_result_value",
                "title": "Lab Test Result",
                "description": "Numeric measures from a laboratory test",
                "datatype": "number",
                "config": {"bins": [200, 300, 500, 1000, 1500, 2000], "minimum": 0, "units": "mg/L"},
                "id": "lab_test_result_value",
                "options": [
                    "< 200",
                    "[200, 300)",
                    "[300, 500)",
                    "[500, 1000)",
                    "[1000, 1500)",
                    "[1500, 2000)",
                    "≥ 2000",
                ],
            },
            {
                "mapping": "individual/phenopackets/measurements",
                "group_by": "assay/id",
                "group_by_value": "NCIT:C16358",
                "value_mapping": "value/quantity/value",
                "title": "BMI",
                "description": "Body Mass Index",
                "datatype": "number",
                "config": {"bins": [18.5, 30], "minimum": 0, "units": "kg/m^2"},
                "id": "bmi",
                "options": ["< 18", "[18, 30)", "≥ 30"],
            },
        ],
    },
    {
        "section_title": "Medical Actions",
        "fields": [
            {
                "mapping": "individual/phenopackets/medical_actions",
                "group_by": "procedure/code/label",
                "title": "Medical Procedures",
                "description": "A clinical procedure performed on a subject",
                "datatype": "string",
                "config": {"enum": None},
                "id": "medical_procedures",
                "options": [
                    "Liver Biopsy",
                    "Magnetic Resonance Imaging",
                    "Positron Emission Tomography",
                    "Punch Biopsy",
                    "X-Ray Imaging",
                ],
            },
            {
                "mapping": "individual/phenopackets/medical_actions",
                "group_by": "treatment/agent/label",
                "title": "Medical Treatments",
                "description": "Treatment with an agent such as a drug",
                "datatype": "string",
                "config": {"enum": None},
                "id": "medical_treatments",
                "options": ["Acetaminophen", "Ibuprofen", "Ondansetron"],
            },
        ],
    },
    {
        "section_title": "Interpretations",
        "fields": [
            {
                "mapping": "individual/phenopackets/interpretations/diagnosis/genomic_interpretations/interpretation_status",
                "title": "Genomic Interpretations",
                "description": "Interpretation for an individual variant or gene (CANDIDATE, CONTRIBUTORY, etc)",
                "datatype": "string",
                "config": {"enum": None},
                "id": "interpretation_status",
                "options": ["CONTRIBUTORY"],
            },
            {
                "mapping": "individual/phenopackets/interpretations/diagnosis/genomic_interpretations/variant_interpretation/acmg_pathogenicity_classification",
                "title": "Variant Pathogenicity",
                "description": "ACMG Pathogenicity category for a particular variant (BENIGN, PATHOGENIC, etc)",
                "datatype": "string",
                "config": {"enum": None},
                "id": "acmg_pathogenicity_classification",
                "options": ["PATHOGENIC"],
            },
        ],
    },
    {
        "section_title": "Experiments",
        "fields": [
            {
                "mapping": "experiment/experiment_type",
                "mapping_for_search_filter": "individual/biosamples/experiment/experiment_type",
                "title": "Experiment Types",
                "description": "Types of experiments performed on a sample",
                "datatype": "string",
                "config": {"enum": None},
                "id": "experiment_type",
                "options": [
                    "Other",
                    "Neutralizing antibody titers",
                    "Metabolite profiling",
                    "RNA-Seq",
                    "WGS",
                    "Proteomic profiling",
                ],
            },
            {
                "mapping": "experiment/study_type",
                "mapping_for_search_filter": "individual/biosamples/experiment/study_type",
                "title": "Study Types",
                "description": "Study type of the experiment (e.g. Genomics, Transcriptomics, etc.)",
                "datatype": "string",
                "config": {"enum": None},
                "id": "experiment_study_type",
                "options": ["Serology", "Genomics", "Other", "Proteomics", "Transcriptomics", "Metabolomics"],
            },
            {
                "mapping": "experiment/experiment_results/file_format",
                "mapping_for_search_filter": "individual/biosamples/experiment/experiment_results/file_format",
                "title": "Results File Types",
                "description": "File type of experiment results files",
                "datatype": "string",
                "config": {"enum": None},
                "id": "experiment_results_file_type",
                "options": ["XLSX", "CRAM", "VCF", "JPEG", "MP4", "DOCX", "CSV", "MARKDOWN"],
            },
        ],
    },
]

KATSU_CONFIG_INTERSECTION = [
    {
        "section_title": "General",
        "fields": [
            {
                "mapping": "individual/age_numeric",
                "title": "Age",
                "description": "Age at arrival",
                "datatype": "number",
                "config": {
                    "bin_size": 10,
                    "taper_left": 10,
                    "taper_right": 100,
                    "units": "years",
                    "minimum": 0,
                    "maximum": 100,
                },
                "id": "age",
                "options": [
                    "< 10",
                    "[10, 20)",
                    "[20, 30)",
                    "[30, 40)",
                    "[40, 50)",
                    "[50, 60)",
                    "[60, 70)",
                    "[70, 80)",
                    "[80, 90)",
                    "[90, 100)",
                ],
            },
            {
                "mapping": "individual/sex",
                "title": "Sex",
                "description": "Sex at birth",
                "datatype": "string",
                "config": {"enum": None},
                "id": "sex",
                "options": ["MALE", "FEMALE"],
            },
        ],
    },
]
