name: Build and push bento_beacon

on:
  release:
    types: [ published ]
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Run Bento build action
        uses: bento-platform/bento_build_action@v0.11.1
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/bento-platform/bento_beacon
          development-dockerfile: dev.Dockerfile
          dockerfile: Dockerfile
